<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MemberDashboardController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\LoanController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// Global Authenticated Routes
Route::middleware('auth')->group(function () {
    Route::get('/notifications', [\App\Http\Controllers\NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/read-all', [\App\Http\Controllers\NotificationController::class, 'markAllAsRead'])->name('notifications.readAll');
    Route::post('/notifications/{id}/read', [\App\Http\Controllers\NotificationController::class, 'markAsRead'])->name('notifications.read');
});

// Nasabah (Member) Routes
Route::middleware(['auth', 'role:member'])->group(function () {
    Route::get('/dashboard', [MemberDashboardController::class, 'index'])->name('dashboard');
    // Loans routes
    Route::get('/loans', [\App\Http\Controllers\MemberLoanController::class, 'index'])->name('loans.index');
    Route::get('/loans/create', [\App\Http\Controllers\MemberLoanController::class, 'create'])->name('loans.create');
    Route::post('/loans', [\App\Http\Controllers\MemberLoanController::class, 'store'])->name('loans.store');
    Route::get('/loans/{id}', [\App\Http\Controllers\MemberInstallmentController::class, 'show'])->name('loans.show');
    Route::post('/installments/{id}/pay', [\App\Http\Controllers\MemberInstallmentController::class, 'pay'])->name('installments.pay');
    
    // Savings routes
    Route::get('/savings', [\App\Http\Controllers\MemberSavingsController::class, 'index'])->name('savings.index');
    Route::post('/savings', [\App\Http\Controllers\MemberSavingsController::class, 'store'])->name('savings.store');
    
    // Profile routes generated by Breeze
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Admin Routes
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    
    // Admin Loans
    Route::get('/loans', [\App\Http\Controllers\AdminLoanController::class, 'index'])->name('loans.index');
    Route::post('/loans/{id}/approve', [\App\Http\Controllers\AdminLoanController::class, 'approve'])->name('loans.approve');
    Route::post('/loans/{id}/reject', [\App\Http\Controllers\AdminLoanController::class, 'reject'])->name('loans.reject');
    
    // Admin Savings
    Route::get('/savings', [\App\Http\Controllers\AdminSavingsController::class, 'index'])->name('savings.index');
    Route::post('/savings/{id}/approve', [\App\Http\Controllers\AdminSavingsController::class, 'approve'])->name('savings.approve');
    Route::post('/savings/{id}/reject', [\App\Http\Controllers\AdminSavingsController::class, 'reject'])->name('savings.reject');
    
    // Admin Installments
    Route::get('/installments', [\App\Http\Controllers\AdminInstallmentController::class, 'index'])->name('installments.index');
    Route::post('/installments/{id}/approve', [\App\Http\Controllers\AdminInstallmentController::class, 'approve'])->name('installments.approve');
    Route::post('/installments/{id}/reject', [\App\Http\Controllers\AdminInstallmentController::class, 'reject'])->name('installments.reject');
    
    // Admin Reports
    Route::get('/reports', [\App\Http\Controllers\AdminReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/loans/export', [\App\Http\Controllers\AdminReportController::class, 'exportLoans'])->name('reports.loans');
    Route::get('/reports/savings/export', [\App\Http\Controllers\AdminReportController::class, 'exportSavings'])->name('reports.savings');
    
    // Admin Users
    Route::get('/users', [\App\Http\Controllers\AdminUserController::class, 'index'])->name('users.index');
    Route::post('/users/{id}/toggle', [\App\Http\Controllers\AdminUserController::class, 'toggleStatus'])->name('users.toggle');
    
    // Admin Pegawai
    Route::get('/pegawai', [\App\Http\Controllers\AdminPegawaiController::class, 'index'])->name('pegawai.index');
    Route::post('/pegawai', [\App\Http\Controllers\AdminPegawaiController::class, 'store'])->name('pegawai.store');
    
    // Admin Master Data (Loan Rules)
    Route::get('/rules', [\App\Http\Controllers\AdminLoanRuleController::class, 'index'])->name('rules.index');
    Route::post('/rules', [\App\Http\Controllers\AdminLoanRuleController::class, 'store'])->name('rules.store');
    Route::post('/rules/{id}/toggle', [\App\Http\Controllers\AdminLoanRuleController::class, 'toggleStatus'])->name('rules.toggle');
});

require __DIR__.'/auth.php';
